backend:
  name: github
  repo: vahizurazov/gatsby-starter-netlify-cms-deploy
  branch: Andrew_dev
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/uploads
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "careers"
    label: "Careers"
    folder: "src/pages/careers"
    create: true
    identifier_field: "career ident"
    slug: "vacancy-{{year}}-{{month}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "careers-page",
        }
      - { label: "Vacancy name", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: section_1_title, widget: string }
          - { label: Image, name: section_1_image, widget: image }
          - { label: BtnText, name: section_1_btn_text, widget: string }
          - { label: Subheading, name: section_1_subheading, widget: string }
          - { label: Content, name: section_1_content, widget: markdown }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/services/index.md"
        label: "Services"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services",
            }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/about-us/index.md"
        label: "About us"
        name: "about-us"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-us-page",
            }
          - { label: section_1_title, name: section_1_title, widget: string }
          - {
              label: section_1_content,
              name: section_1_content,
              widget: string,
            }
          - { label: section_1_Image, name: section_1_image, widget: image }

          - { label: section_2_text, name: section_2_text, widget: string }
          - { label: section_2_image, name: section_2_image, widget: image }

          - { label: section_3_title, name: section_3_title, widget: string }
          - { label: section_3_text, name: section_3_text, widget: string }
      - file: "src/pages/contact-us/index.md"
        label: "Contact us"
        name: "contact-us"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-us-page",
            }
          - { label: section_1_title, name: section_1_title, widget: string }
          - {
              label: section_1_content,
              name: section_1_content,
              widget: string,
            }
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/config/website.md"
        label: "Settings"
        name: "settings"
        fields:
          -  {
              label: "Config Key",
              name: "configKey",
              widget: "hidden",
              default: "site-config",
            }
          - {
              label: Site Title,
              name: siteTitle,
              widget: string,
            }
          - {
              label: Site Title Short,
              name: siteTitleShort,
              widget: string,
            }
          - {
              label: Site Title Alt,
              name: siteTitleAlt,
              widget: string,
            }
          - {
              label: Organization,
              name: organization,
              widget: string,
            }
          - {
              label: Author,
              name: author,
              widget: string,
            }
          - {
              label: Site Logo,
              name: siteLogo,
              widget: string,
            }
          - {
              label: Site Url,
              name: siteUrl,
              widget: string,
            }
          - {
              label: Path Prefix,
              name: pathPrefix,
              widget: string,
            }
          - {
              label: Blog Prefix,
              name: blogPrefix,
              widget: string,
            }
          - {
              label: Amp Prefix,
              name: ampPrefix,
              widget: string,
            }
          - {
              label: Vacancy Prefix,
              name: vacancyPrefix,
              widget: string,
            }
          - {
              label: Site Description,
              name: siteDescription,
              widget: string,
            }
          - {
              label: Google Analytics ID,
              name: googleAnalyticsID,
              widget: string,
            }
          - {
              label: Theme Color,
              name: themeColor,
              widget: string,
            }
          - {
              label: Background Color,
              name: backgroundColor,
              widget: string,
            }
